#!/bin/sh
# add-library.sh - add a library folder to The Vault (local folder or SMB/CIFS share)
#
#   sh add-library.sh           # interactive
#   sh add-library.sh --list    # show configured extra libraries
#
# How it works: your primary library still comes from .env / docker-compose.yml.
# This script manages EXTRA libraries in a generated `docker-compose.override.yml`
# (Docker Compose merges it automatically), recorded in `.vault-libraries`.
# Re-run it any time to add more. Each library is mounted read-only at
# /library/<name> inside the container and picked up on the next scan.
#
# Network shares on Synology: the most reliable way is to mount the share in
# DSM first (File Station → Tools → Mount Remote Folder → CIFS Shared Folder),
# then add the mount point here as a LOCAL folder (choice 1), e.g.
# /volume1/remote/endor. DSM keeps the credentials and reconnects for you.

set -eu

# Records and the override may hold SMB passwords: create them private.
umask 077

DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"
RECORDS=".vault-libraries"
OVERRIDE="docker-compose.override.yml"

PATH="$PATH:/usr/local/bin"
export PATH

as_root() { if [ "$(id -u)" = "0" ]; then "$@"; else sudo "$@"; fi; }

slug() { printf '%s' "$1" | tr '[:upper:] ' '[:lower:]_' | tr -cd 'a-z0-9_'; }

# Escape a value for a double-quoted YAML string that Compose also
# interpolates: \ and " for YAML, $ -> $$ so Compose keeps it literal.
esc() { printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' -e 's/\$/$$/g'; }

volname() {
  s="$(slug "$1")"
  [ -n "$s" ] || s="$(printf '%s' "$1" | cksum | cut -d' ' -f1)"
  printf 'lib_%s' "$s"
}

restore_echo() { if [ -t 0 ]; then stty echo 2>/dev/null || true; fi; }
trap restore_echo EXIT INT TERM

regenerate() {
  # Rebuild docker-compose.override.yml from every record in $RECORDS
  {
    printf '%s\n' "# Generated by add-library.sh - managed file, do not edit by hand."
    printf '%s\n' "# Extra library folders mounted in addition to the primary one in docker-compose.yml."
    printf '%s\n' "services:"
    printf '%s\n' "  backend:"
    printf '%s\n' "    volumes:"
    while IFS='|' read -r type name a b c d; do
      [ -z "$type" ] && continue
      if [ "$type" = "local" ]; then
        printf '%s\n' "      - \"$(esc "$a"):/library/$(esc "$name"):ro\""
      else
        printf '%s\n' "      - \"$(volname "$name"):/library/$(esc "$name"):ro\""
      fi
    done < "$RECORDS"

    # Named CIFS volumes for any SMB records
    HAS_SMB=0
    while IFS='|' read -r type name a b c d; do
      if [ "$type" = "smb" ]; then HAS_SMB=1; fi
    done < "$RECORDS"

    if [ "$HAS_SMB" = "1" ]; then
      printf '%s\n' "volumes:"
      while IFS='|' read -r type name a b c d; do
        [ "$type" = "smb" ] || continue
        if [ -n "$c" ]; then CRED="username=$c,password=$d"; else CRED="guest"; fi
        printf '%s\n' "  $(volname "$name"):"
        printf '%s\n' "    driver: local"
        printf '%s\n' "    driver_opts:"
        printf '%s\n' "      type: cifs"
        printf '%s\n' "      device: \"//$(esc "$a")/$(esc "$b")\""
        printf '%s\n' "      o: \"$(esc "$CRED"),vers=3.0,ro,uid=1000,gid=1000,iocharset=utf8,nounix,noserverino\""
      done < "$RECORDS"
    fi
  } > "$OVERRIDE"
  chmod 600 "$OVERRIDE" 2>/dev/null || true
}

list_libraries() {
  if [ ! -s "$RECORDS" ]; then echo "No extra libraries configured yet."; return; fi
  echo "Configured extra libraries:"
  while IFS='|' read -r type name a b c d; do
    [ -z "$type" ] && continue
    if [ "$type" = "local" ]; then
      printf '%s\n' "  • [$name]  local: $a"
    else
      printf '%s\n' "  • [$name]  smb:   //$a/$b  (user: ${c:-guest})"
    fi
  done < "$RECORDS"
}

drop_record() {  # remove any existing record with this label
  awk -F'|' -v n="$1" '$2 != n' "$RECORDS" > "$RECORDS.tmp" || true
  cat "$RECORDS.tmp" > "$RECORDS"
  rm -f "$RECORDS.tmp"
}

# reject VALUE WHAT CHARS... : fail if VALUE contains any of the characters
reject() {
  val="$1"; what="$2"; shift 2
  for ch in "$@"; do
    case "$val" in
      *"$ch"*) echo "✗ The $what may not contain '$ch'."; return 1 ;;
    esac
  done
  return 0
}

touch "$RECORDS"
chmod 600 "$RECORDS" 2>/dev/null || true

if [ "${1:-}" = "--list" ]; then list_libraries; exit 0; fi

echo ""
echo "┌─────────────────────────────────────┐"
echo "│   The Vault - add a library folder  │"
echo "└─────────────────────────────────────┘"
echo ""
list_libraries
echo ""
echo "What do you want to add?"
echo "  1) A folder on THIS machine (local path) - also use this for a share"
echo "     you mounted with DSM 'Mount Remote Folder' (recommended on Synology)"
echo "  2) A folder on ANOTHER computer/NAS over the network (SMB / CIFS)"
printf "Choice [1/2]: "
read -r CHOICE

printf "A short label for it (shows in the app, e.g. Endor): "
read -r NAME
[ -z "$NAME" ] && { echo "A label is required."; exit 1; }
reject "$NAME" "label" "|" "/" ":" '"' || exit 1

if [ "$CHOICE" = "1" ]; then
  printf "Full path to the folder on this machine (e.g. /volume1/More Prints): "
  read -r LPATH
  [ -n "$LPATH" ] || { echo "A path is required."; exit 1; }
  reject "$LPATH" "path" "|" ":" '"' || exit 1
  [ -d "$LPATH" ] || echo "  (heads up: '$LPATH' isn't a folder on this machine right now - continuing anyway)"
  drop_record "$NAME"
  printf '%s\n' "local|$NAME|$LPATH|||" >> "$RECORDS"
else
  echo ""
  echo "Tip (Synology): DSM's File Station → Tools → Mount Remote Folder is more"
  echo "robust than a Docker CIFS volume; mount it there and choose option 1 instead."
  echo ""
  echo "SMB details. Tip: on a Mac the share smb://endor._smb._tcp.local/3dPrint"
  echo "means host = endor (use its IP to be safe) and share = 3dPrint."
  printf "Server IP or hostname (e.g. 192.168.1.168): "
  read -r SHOST
  reject "$SHOST" "server name" "|" "/" "," " " '"' || exit 1
  printf "Share name (e.g. 3dPrint): "
  read -r SSHARE
  reject "$SSHARE" "share name" "|" "," '"' || exit 1
  printf "Username (leave blank for guest): "
  read -r SUSER
  SPASS=""
  if [ -n "$SUSER" ]; then
    reject "$SUSER" "username" "|" "," '"' || exit 1
    printf "Password: "
    if [ -t 0 ]; then stty -echo 2>/dev/null || true; fi
    read -r SPASS
    restore_echo
    echo ""
    case "$SPASS" in
      *,*)
        echo "✗ This password contains a comma. Docker's CIFS mount options are"
        echo "  comma-separated, so it can't be passed safely."
        echo "  Use DSM instead: File Station → Tools → Mount Remote Folder → CIFS,"
        echo "  then re-run this script and add the mount point as a LOCAL folder (1)."
        exit 1 ;;
    esac
    reject "$SPASS" "password" "|" '"' || exit 1
  fi
  drop_record "$NAME"
  printf '%s\n' "smb|$NAME|$SHOST|$SSHARE|$SUSER|$SPASS" >> "$RECORDS"
fi

regenerate

echo ""
echo "▸ Updated $OVERRIDE"
echo "▸ Restarting The Vault..."
as_root env PATH="$PATH" sh -c 'if docker compose version >/dev/null 2>&1; then docker compose up -d; else docker-compose up -d; fi'

echo ""
echo "✓ '$NAME' is mounted at /library/$NAME."
echo "  Open the app → ⟳ SCAN LIBRARY → you should see '$NAME' in the mounted folders. Scan it to index."
echo ""
echo "  (Re-run sh add-library.sh to add more, or sh add-library.sh --list to review.)"
