#!/bin/sh
# add-library.sh — add a library folder to The Vault (local folder or SMB/CIFS share)
#
#   ./add-library.sh           # interactive
#   ./add-library.sh --list    # show configured extra libraries
#
# How it works: your primary library still comes from .env / docker-compose.yml.
# This script manages EXTRA libraries in a generated `docker-compose.override.yml`
# (Docker Compose merges it automatically), recorded in `.vault-libraries`.
# Re-run it any time to add more. Each library is mounted read-only at
# /library/<name> inside the container and picked up on the next scan.

set -e

DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR"
RECORDS=".vault-libraries"
OVERRIDE="docker-compose.override.yml"

# Pick the compose command (v2 preferred)
COMPOSE="docker-compose"
if docker compose version >/dev/null 2>&1; then COMPOSE="docker compose"; fi

slug() { printf '%s' "$1" | tr '[:upper:] ' '[:lower:]_' | tr -cd 'a-z0-9_'; }

regenerate() {
  # Rebuild docker-compose.override.yml from every record in $RECORDS
  {
    echo "# Generated by add-library.sh — managed file, do not edit by hand."
    echo "# Extra library folders mounted in addition to the primary one in docker-compose.yml."
    echo "services:"
    echo "  backend:"
    echo "    volumes:"
    while IFS='|' read -r type name a b c d; do
      [ -z "$type" ] && continue
      if [ "$type" = "local" ]; then
        echo "      - \"$a:/library/$name:ro\""
      else
        echo "      - \"lib_$(slug "$name"):/library/$name:ro\""
      fi
    done < "$RECORDS"

    # Named CIFS volumes for any SMB records
    HAS_SMB=0
    while IFS='|' read -r type name a b c d; do
      [ "$type" = "smb" ] && HAS_SMB=1
    done < "$RECORDS"

    if [ "$HAS_SMB" = "1" ]; then
      echo "volumes:"
      while IFS='|' read -r type name a b c d; do
        [ "$type" = "smb" ] || continue
        if [ -n "$c" ]; then CRED="username=$c,password=$d"; else CRED="guest"; fi
        echo "  lib_$(slug "$name"):"
        echo "    driver: local"
        echo "    driver_opts:"
        echo "      type: cifs"
        echo "      device: \"//$a/$b\""
        echo "      o: \"$CRED,vers=3.0,ro,uid=1000,gid=1000,iocharset=utf8,nounix,noserverino\""
      done < "$RECORDS"
    fi
  } > "$OVERRIDE"
  chmod 600 "$OVERRIDE" 2>/dev/null || true
}

list_libraries() {
  if [ ! -s "$RECORDS" ]; then echo "No extra libraries configured yet."; return; fi
  echo "Configured extra libraries:"
  while IFS='|' read -r type name a b c d; do
    [ -z "$type" ] && continue
    if [ "$type" = "local" ]; then
      echo "  • [$name]  local: $a"
    else
      echo "  • [$name]  smb:   //$a/$b  (user: ${c:-guest})"
    fi
  done < "$RECORDS"
}

touch "$RECORDS"

if [ "$1" = "--list" ]; then list_libraries; exit 0; fi

echo ""
echo "┌─────────────────────────────────────┐"
echo "│   The Vault — add a library folder  │"
echo "└─────────────────────────────────────┘"
echo ""
list_libraries
echo ""
echo "What do you want to add?"
echo "  1) A folder on THIS machine (local path)"
echo "  2) A folder on ANOTHER computer/NAS over the network (SMB / CIFS)"
printf "Choice [1/2]: "
read CHOICE

printf "A short label for it (shows in the app, e.g. Endor): "
read NAME
[ -z "$NAME" ] && { echo "A label is required."; exit 1; }

if [ "$CHOICE" = "1" ]; then
  printf "Full path to the folder on this machine (e.g. /volume1/More Prints): "
  read LPATH
  [ -d "$LPATH" ] || echo "  (heads up: '$LPATH' isn't a folder on this machine right now — continuing anyway)"
  # drop any existing record with the same name, then append
  grep -v "^local|$NAME|" "$RECORDS" 2>/dev/null | grep -v "^smb|$NAME|" > "$RECORDS.tmp" || true
  mv "$RECORDS.tmp" "$RECORDS"
  echo "local|$NAME|$LPATH|||" >> "$RECORDS"
else
  echo ""
  echo "SMB details. Tip: on a Mac the share smb://endor._smb._tcp.local/3dPrint"
  echo "means host = endor (use its IP to be safe) and share = 3dPrint."
  printf "Server IP or hostname (e.g. 192.168.1.168): "
  read SHOST
  printf "Share name (e.g. 3dPrint): "
  read SSHARE
  printf "Username (leave blank for guest): "
  read SUSER
  if [ -n "$SUSER" ]; then printf "Password: "; stty -echo 2>/dev/null; read SPASS; stty echo 2>/dev/null; echo ""; else SPASS=""; fi
  grep -v "^local|$NAME|" "$RECORDS" 2>/dev/null | grep -v "^smb|$NAME|" > "$RECORDS.tmp" || true
  mv "$RECORDS.tmp" "$RECORDS"
  echo "smb|$NAME|$SHOST|$SSHARE|$SUSER|$SPASS" >> "$RECORDS"
fi

regenerate

echo ""
echo "▸ Updated $OVERRIDE"
echo "▸ Restarting The Vault..."
sudo $COMPOSE up -d

echo ""
echo "✓ '$NAME' is mounted at /library/$NAME."
echo "  Open the app → ⟳ SCAN LIBRARY → you should see '$NAME' in the mounted folders. Scan it to index."
echo ""
echo "  (Re-run ./add-library.sh to add more, or ./add-library.sh --list to review.)"
